import { build } from 'esbuild';
import { copyFile, readFile, writeFile } from 'node:fs/promises';
import { posix } from 'node:path';
import { parse, stringify } from 'yaml';

// Preserve the published /action entrypoint without maintaining a second input/output contract.
const actionMetadata = parse(await readFile('action.yml', 'utf8'));
const subdirectoryMetadata = {
  ...actionMetadata,
  runs: {
    ...actionMetadata.runs,
    main: posix.relative('action', actionMetadata.runs.main),
    post: posix.relative('action', actionMetadata.runs.post),
  },
};
await writeFile('action/action.yml', '# Generated by npm run build. Edit the root action.yml instead.\n' + stringify(subdirectoryMetadata, { lineWidth: 0 }));

await build({
  entryPoints: { index: 'src/action-entry.ts', cleanup: 'src/post-action-entry.ts' },
  bundle: true,
  platform: 'node',
  target: 'node24',
  format: 'cjs',
  outdir: 'action/dist',
  outExtension: { '.js': '.cjs' },
  legalComments: 'eof',
  banner: { js: '// Generated by npm run build. Edit src/ rather than this bundle.' },
});
await copyFile('node_modules/yaml/LICENSE', 'action/dist/LICENSE.yaml');
